/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 1
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "/home/thailuu/results/fast_lio2_map.pcd"

        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 1          # 1 = Livox series
            scan_line: 6
            blind: 2.0

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree: 360.0
            det_range: 450.0
            extrinsic_est_en: false
            # R-Campus: Livox Avia extrinsics from RESPLE config (t_lb sign-flipped)
            extrinsic_T: [ 0.04165, 0.02326, -0.0284 ]
            extrinsic_R: [ 1., 0., 0.,
                           0., 1., 0.,
                           0., 0., 1. ]

        publish:
            path_en: true
            scan_publish_en: true
            dense_publish_en: false
            scan_bodyframe_pub_en: false

        pcd_save:
            pcd_save_en: false
            interval: -1
